//Places
export const GET_PLACES_REQUEST = 'GET_PLACES_REQUEST';
export const GET_PLACES_SUCCESS = 'GET_PLACES_SUCCESS';
export const GET_PLACES_FAILURE = 'GET_PLACES_FAILURE';

export const ADD_PLACE_REQUEST = 'ADD_PLACE_REQUEST';
export const ADD_PLACE_SUCCESS = 'ADD_PLACE_SUCCESS';
export const ADD_PLACE_FAILURE = 'ADD_PLACE_FAILURE';

export const DELETE_PLACE_REQUEST = 'DELETE_PLACE_REQUEST';
export const DELETE_PLACE_SUCCESS = 'DELETE_PLACE_SUCCESS';
export const DELETE_PLACE_FAILURE = 'DELETE_PLACE_FAILURE';

//Decisions
export const GET_DECISIONS_REQUEST = 'GET_DECISIONS_REQUEST';
export const GET_DECISIONS_SUCCESS = 'GET_DECISIONS_SUCCESS';
export const GET_DECISIONS_FAILURE = 'GET_DECISIONS_FAILURE';

//People
export const GET_PEOPLE_REQUEST = 'GET_PEOPLE_REQUEST';
export const GET_PEOPLE_SUCCESS = 'GET_PEOPLE_SUCCESS';
export const GET_PEOPLE_FAILURE = 'GET_PEOPLE_FAILURE';

export const ADD_PEOPLE_REQUEST = 'ADD_PEOPLE_REQUEST';
export const ADD_PEOPLE_SUCCESS = 'ADD_PEOPLE_SUCCESS';
export const ADD_PEOPLE_FAILURE = 'ADD_PEOPLE_FAILURE';

export const DELETE_PEOPLE_REQUEST = 'DELETE_PEOPLE_REQUEST';
export const DELETE_PEOPLE_SUCCESS = 'DELETE_PEOPLE_SUCCESS';
export const DELETE_PEOPLE_FAILURE = 'DELETE_PEOPLE_FAILURE';